FROM golang:1.10-alpine AS build-stage
RUN apk update && apk add binutils
COPY app-smaller.go .
RUN go build -o /app app-smaller.go
RUN strip /app
FROM scratch
COPY --from=build-stage /app /
CMD [ "/app" ]
